### ISSUE TITLE
curl commands for executing api

### ISSUE THREAD

**Issue by ckulkarni-cribl** [Ravi-D/Log-Collection-Simple-REST-API#2]
Hi Ravi,

could you provide curl commands to execute that showcase different functionality provided by this project? I also noticed port is not provided in case of running from command line, could you set a default port and document that?

**Comment by Ravi-D** [comment]
I believe the Swagger UI generates the corresponding curl command when you submit the GET request, but I can point this out/display a couple different calls, sure. Yeah port behavior hasn't been addressed so I can take a look at that.
