### ISSUE TITLE
Default value for linesRequested

### ISSUE THREAD

**Issue by ckulkarni-cribl** [Ravi-D/Log-Collection-Simple-REST-API#3]
Hi Ravi,

I dont think this condition makes sense, no of lines is not comparable to file size, could we make this condition better?
```
            bool returnEntireFile = ((linesRequested == null || linesRequested > fileSize) && string.IsNullOrWhiteSpace(keyword));
```

also in case the linesRequested is not provided in the query, can we default to a number that's reasonable?

**Comment by Ravi-D** [comment]
I assumed based on the prompt that if no lines are given, the entire file - no matter the size - has been requested. For performance's sake I can definitely fall back to a safe default if needed. I thought this behavior was in line with the "performance" consideration and my solution being stress tested for files above 1GB. 

You're right - I was originally planning on dividing the fileSize value by a number that would make this a usable condition.
