### ISSUE TITLE
Not loading all data in memory

### ISSUE THREAD

**Issue by ckulkarni-cribl** [Ravi-D/Log-Collection-Simple-REST-API#6]
Hi Ravi,

I'm a bit unfamiliar with .net internals, so correct me if i'm reading it wrong - 
```
            foreach (string line in File.ReadLines(fullPath).Reverse())
```
ReadLines does work with `IEnumerable` and can read data incrementally, but Reversing it will force reading all the data in memory. So Above line will read all data in memory first and then reverse it? 

If this not true, feel free to close the issue. Otherwise can we make it more performant?

**Comment by Ravi-D** [comment]
That's a good point actually, I didn't think Reverse() would do that, but I think you are right. In VS you would probably see the memory usage spike during this part, more than expected. This is specifically what I wanted to avoid, so I will be addressing this and the application crashing first.

**Comment by Ravi-D** [comment]
fixed in latest PR
